#!/bin/sh
echo "CTRL-VIM by Mikey D"
echo "installing..."
echo "WARNING, This installation will destroy your existing .vimrc file! I suggest making a backup. Do you wish to continue?(y or n) [ENTER]:"
read choice
case $choice in
    [Nn]* ) exit;;
    * ) echo "proceeding with install. you have chosen wisely."
esac

sudo apt-get install vim silversearcher-ag
mkdir -p ~/.vim/bundle
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
echo 'stty -ixon' >> ~/.bashrc
cp .vimrc ~/.vimrc
vim -c ":PluginInstall" README.md

echo "...install complete."
