#!/bin/sh
echo "GUNGNIR"
echo "installing..."
echo "WARNING, This installation will destroy your existing .vimrc file! \nDo you wish to continue?(y or n) [ENTER]:"
read choice
case $choice in
    [Nn]* ) echo 'Aborting.'; exit;;
    [Yy]* ) echo "proceeding with install. you have chosen wisely.";;
    * ) echo 'Aborting.'; exit;; 
esac

echo 'stty -ixon' >> ~/.bashrc
cp .lightvimrc ~/.vimrc

echo "...install complete. Enjoy! ~Mike"
echo "IMPORTANT: you must run 'source ~/.bashrc' to enable all features"
