#!/bin/sh
echo "GUNGNIR"
echo "installing..."
echo "WARNING, This installation will replace your existing .vimrc file! Your original .vimrc file will be backed up to ~/.vimrc_warpcore_bak. \nDo you wish to continue?(y or n) [ENTER]:"
read choice
case $choice in
    [Nn]* ) echo 'Aborting.'; exit;;
    [Yy]* ) echo "proceeding with install. you have chosen wisely.";;
    * ) echo 'Aborting.'; exit;; 
esac

sudo apt-get install vim silversearcher-ag exuberant-ctags
mkdir -p ~/.config/nvim/bundle
git clone https://github.com/VundleVim/Vundle.vim.git ~/.config/nvim/bundle/Vundle.vim
echo 'stty -ixon' >> ~/.bashrc
echo 'stty -ixon' >> ~/.zshrc
cp ~/.config/nvim/init.vim ~/.config/nvim/init.vim.back
cp neovim_init.vim ~/.config/nvim/init.vim
nvim -c ":PluginInstall" -c "qa!" README.md


echo "...install complete. Enjoy!"
echo "IMPORTANT: you must run 'source ~/.bashrc' to enable all features"
