#!/bin/sh
echo "GUNGNIR"
echo "installing..."
echo "WARNING, This installation will replace your existing .vimrc file! Your original .vimrc file will be backed up to ~/.vimrc_warpcore_bak. \nDo you wish to continue?(y or n) [ENTER]:"
read choice
case $choice in
    [Nn]* ) echo 'Aborting.'; exit;;
    [Yy]* ) echo "proceeding with install. you have chosen wisely.";;
    * ) echo 'Aborting.'; exit;; 
esac

sudo apt-get install vim silversearcher-ag exuberant-ctags
mkdir -p ~/.vim/bundle
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
echo 'stty -ixon' >> ~/.bashrc
cp ~/.vimrc ~/.vimrc_warpcore_bak
cp .warpcore_vimrc ~/.vimrc
vim -c ":PluginInstall" -c "qa!" README.md


echo "...install complete. Enjoy! ~Mike"
echo "IMPORTANT: you must run 'source ~/.bashrc' to enable all features"
